[[language]]
name = "nix"
auto-format = true
formatter = {command = "alejandra"}

[[language]]
name = "svelte"
language-servers = ["svelteserver", "tailwindcss-ls"]

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "vscode-eslint-language-server"]
# formatter = { command = "dprint", args = [ "fmt", "--stdin", "js" ] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]
# formatter = { command = "dprint", args = [ "fmt", "--stdin", "ts" ] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]
# formatter = { command = "dprint", args = [ "fmt", "--stdin", "tsx" ] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]
# formatter = { command = "dprint", args = [ "fmt", "--stdin", "jsx" ] }
auto-format = true

[[language]]
name = "json"
# formatter = { command = "dprint", args = [ "fmt", "--stdin", "json" ] }
auto-format = true

[[language]]
name = "java"
language-servers = ["jdtls"]
auto-format = true

[language-server.rust-analyzer.config]
check.command = "clippy"

[language-server.jdtls]
command = "jdtls"
