[package]
name = "gpu-control"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
env_logger = "0.11.8"
futures-lite = "2.6.1"
log = "0.4.29"
nix = { version = "0.30.1", features = ["fs", "signal", "process"] }
notify-rust = "4.11.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.17"
tokio = { version = "1.49.0", features = ["full"] }
tokio-udev = "0.10.0"
