[package]
name = "lan-mouse-grab"
version = "0.1.0"
edition = "2021"

[dependencies]
input-event = { git = "https://github.com/feschber/lan-mouse", default-features = false }
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client", "staging", "unstable"] }
wayland-protocols-wlr = { version = "0.3", features = ["client"] }

gstreamer = { version = "0.25", features = ["v1_24"] }
gstreamer-app = { version = "0.25", features = ["v1_24"] }
gstreamer-video = { version = "0.25", features = ["v1_24"] }
gstreamer-allocators = { version = "0.25", features = ["v1_24"] }
bluer = { version = "0.17", features = ["bluetoothd", "l2cap", "rfcomm"] }
futures = "0.3"

tokio = { version = "1", features = ["rt", "rt-multi-thread", "net", "sync", "time", "signal", "macros"] }

libc = "0.2"
anyhow = "1"
log = "0.4"
env_logger = "0.11"
tempfile = "3"
uuid = { version = "1.21.0", features = ["v4"] }

[profile.release]
codegen-units = 1
lto = "fat"
strip = true
panic = "abort"
